# Dropout Regularization to help with Overfitting

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("./sonar_dataset.csv", header=None)
df

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
0    0.0090  0.0032   R  
1    0.0052  0.0044   R  
2    0.0095  0.0078   R  
3    0.0040  0.0117   R  
4    0.0107  0.0094   R  
..      ...     ...  ..  
203  0.0193  0.0157   M  
204  0.0062  0.0067   M  
205  0.0077  0.0031   M  
206  0.0036  0.0048   M  
207  0.0061  0.0115   M  

[208 rows x 61 columns]

In [4]:
df.shape

(208, 61)

In [5]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [6]:
df.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60],
      dtype='int64')

In [7]:
df[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [8]:
X = df.drop(60, axis='columns')
y = df[60]

In [9]:
X

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      50      51      52      53      54      55      56  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065   
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034   
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140   
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034   
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040   

         57      58      59  
0    0.0084  0.0090  0.0032  
1    0.0049  0.0052  0.0044  
2    0.0164  0.0095  0.0078  
3    0.0044  0.0040  0.0117  
4    0.0048  0.0107  0.0094  
..      ...     ...     ...  
203  0.0115  0.0193  0.0157  
204  0.0032  0.0062  0.0067  
205  0.0138  0.0077  0.0031  
206  0.0079  0.0036  0.0048  
207  0.0036  0.0061  0.0115  

[208 rows x 60 columns]

In [10]:
y

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

### Using one hot encoding

In [11]:
y = pd.get_dummies(y, drop_first=True)
y.sample(5)

R
177  False
90    True
128  False
101  False
70    True

In [12]:
# Convert boolean values to integer
y = y[y.select_dtypes(include=['bool']).columns].astype(int)
# R --> 1 and M --> 0
y

R
0    1
1    1
2    1
3    1
4    1
..  ..
203  0
204  0
205  0
206  0
207  0

[208 rows x 1 columns]

In [13]:
y.value_counts()

R
0    111
1     97
Name: count, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [15]:
X_train.shape, y_train.shape

((156, 60), (156, 1))

In [16]:
X_test.shape, y_test.shape

((52, 60), (52, 1))

In [17]:
import tensorflow as tf
from tensorflow import keras

In [18]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.6930 - accuracy: 0.4615
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6761 - accuracy: 0.5513
Epoch 3/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6599 - accuracy: 0.5769
Epoch 4/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6292 - accuracy: 0.6667
Epoch 5/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5976 - accuracy: 0.7756
Epoch 6/100
20/20 [==============================] - 0s 957us/step - loss: 0.5638 - accuracy: 0.7179
Epoch 7/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5382 - accuracy: 0.8077
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4936 - accuracy: 0.7949
Epoch 9/100
20/20 [==============================] - 0s 875us/step - loss: 0.4609 - accuracy: 0.8462
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4507 - accuracy: 0.7692
Epoch

20/20 [==============================] - 0s 1ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 83/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 692us/step - loss: 0.0043 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 814us/step - loss: 0.0039 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0036 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0034 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0035 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0028 - accuracy: 1.0000
Epoch 92/

In [19]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 3ms/step - loss: 1.1908 - accuracy: 0.7308


[1.1908124685287476, 0.7307692170143127]

In [20]:
y_pred = model.predict(X_test).reshape(-1)
y_pred[:10]

2/2 [==============================] - 0s 2ms/step


array([1.1530168e-11, 8.5783565e-01, 7.7372289e-01, 5.5705544e-07,
       9.9999905e-01, 9.9991012e-01, 1.0004579e-02, 9.9999857e-01,
       6.4042872e-08, 9.9999946e-01], dtype=float32)

In [21]:
# Round the values to nearest integer i.e, 0 to 1
y_pred = np.round(y_pred)
y_pred[:10]

array([0., 1., 1., 0., 1., 1., 0., 1., 0., 1.], dtype=float32)

In [22]:
y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [23]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.70      0.85      0.77        27
           1       0.79      0.60      0.68        25

    accuracy                           0.73        52
   macro avg       0.74      0.73      0.72        52
weighted avg       0.74      0.73      0.73        52



### Adding Dropout layer

In [24]:
modeld = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid')
])

modeld.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

modeld.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.7130 - accuracy: 0.4872
Epoch 2/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7275 - accuracy: 0.4872
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6901 - accuracy: 0.5256
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7175 - accuracy: 0.4808
Epoch 5/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6675 - accuracy: 0.6026
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6556 - accuracy: 0.6026
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6919 - accuracy: 0.5256
Epoch 8/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6693 - accuracy: 0.5897
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6594 - accuracy: 0.5962
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6743 - accuracy: 0.5641
Epoch 11/

Epoch 83/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3358 - accuracy: 0.8782
Epoch 84/100
20/20 [==============================] - 0s 1ms/step - loss: 0.3465 - accuracy: 0.8590
Epoch 85/100
20/20 [==============================] - 0s 1ms/step - loss: 0.3603 - accuracy: 0.8526
Epoch 86/100
20/20 [==============================] - 0s 1ms/step - loss: 0.3377 - accuracy: 0.8654
Epoch 87/100
20/20 [==============================] - 0s 1ms/step - loss: 0.4088 - accuracy: 0.8654
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3468 - accuracy: 0.8782
Epoch 89/100
20/20 [==============================] - 0s 1ms/step - loss: 0.3419 - accuracy: 0.8333
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2898 - accuracy: 0.8910
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3157 - accuracy: 0.8846
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3277 - accuracy: 0.8590


In [25]:
modeld.evaluate(X_test, y_test)

2/2 [==============================] - 0s 19ms/step - loss: 0.4825 - accuracy: 0.8077


[0.4825473427772522, 0.807692289352417]

In [26]:
y_pred1 = modeld.predict(X_test).reshape(-1)
y_pred1[:10]

2/2 [==============================] - 0s 2ms/step


array([3.1291631e-05, 7.0164323e-01, 9.0097052e-01, 6.7043365e-03,
       9.9711305e-01, 9.2901134e-01, 3.2550275e-01, 9.9662483e-01,
       1.2078307e-02, 9.9846375e-01], dtype=float32)

In [27]:
# Round the values to nearest integer i.e, 0 to 1
y_pred1 = np.round(y_pred1)
y_pred1[:10]

array([0., 1., 1., 0., 1., 1., 0., 1., 0., 1.], dtype=float32)

In [28]:
y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [29]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.77      0.89      0.83        27
           1       0.86      0.72      0.78        25

    accuracy                           0.81        52
   macro avg       0.82      0.80      0.81        52
weighted avg       0.81      0.81      0.81        52

