# Word Embeddings using keras embedding layer

In [12]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [13]:
reviews = ['nice food', 
          'amazing restaurant',
           'too good',
          'just loved it!', 
          'will go again',
          'horrible food',
          'never go there',
          'poor service',
          'poor quality',
          'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [14]:
one_hot("amazing restaurant", 30)

[20, 5]

In [15]:
one_hot("amazing restaurant", 100)

[29, 22]

In [16]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[20, 22], [20, 5], [20, 27], [13, 24, 21], [14, 18, 4], [2, 22], [6, 18, 3], [13, 19], [13, 16], [19, 10]]


In [17]:
# Add padding to make the all reviews length same
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[20 22  0  0]
 [20  5  0  0]
 [20 27  0  0]
 [13 24 21  0]
 [14 18  4  0]
 [ 2 22  0  0]
 [ 6 18  3  0]
 [13 19  0  0]
 [13 16  0  0]
 [19 10  0  0]]


In [18]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

C:\Users\suman\anaconda3\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
X = padded_reviews
y = sentiment

In [20]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.fit(X, y, epochs=50, verbose=0)

In [22]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step - accuracy: 1.0000 - loss: 0.6397


1.0

In [23]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [24]:
weights[13]

array([-0.00875109,  0.01043984, -0.04904566, -0.02225066, -0.07375326],
      dtype=float32)

In [25]:
weights[5]

array([-0.06634249,  0.02179751, -0.06913447,  0.08414565, -0.02392234],
      dtype=float32)

In [26]:
weights[16]

array([ 0.09712842, -0.01268217,  0.00611099, -0.097311  ,  0.02948462],
      dtype=float32)

In [27]:
weights[2]

array([ 0.05439301,  0.06494495, -0.07134096, -0.06944999, -0.05348371],
      dtype=float32)